name: Build and Sign

on:
  workflow_dispatch:
    inputs:

      source_branch:
        description: 'The source branch or ref to build from'
        default: 'main'
        required: true

      release_name:
        description: 'The name for the release'
        required: true


env:
  SOURCE_REPOSITORY: 'AbdulrhmanGoni/denokv-gui-client'
  SOURCE_REPOSITORY_NAME: 'denokv-gui-client'
  NODE_NO_WARNINGS: 1
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  npm_config_fund: false
  USE_HARD_LINKS: false
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    environment: OSSign
    runs-on: windows-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: ${{ env.SOURCE_REPOSITORY }}
          ref: ${{ github.event.inputs.source_branch }}
          fetch-depth: 1

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.15.0"

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: "11.15.1"

      - name: Install dependencies
        run: pnpm ci

      - name: Build the app
        env:
          OSSIGN_CONFIG: ${{ secrets.OSSIGN_CONFIG }}
        run: pnpm run compile --win --publish never

      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: |
            dist/latest.yml
            dist/denokv-gui-client*.exe
            dist/denokv-gui-client*.exe.blockmap
          name: ${{ github.event.inputs.release_name }}
          tag_name: ${{ github.run_id }}
          body: |
            <img src="https://github.com/ossign.png" alt="OSSign Logo" width="100" height="100" />
            # Signed Release ${{ github.event.inputs.release_name }}
            
            These are the distributable files for the signed release of ${{ env.SOURCE_REPOSITORY_NAME }} ${{ github.event.inputs.release_name }}

            The source code was fetched from https://github.com/${{ env.SOURCE_REPOSITORY }}/tree/${{ github.event.inputs.source_branch }}
